### ISSUE TITLE
Change money amount removes all trade items

### ISSUE THREAD

**Issue by CodingAir** [CodingAir/TradeSystem#101]
I found another big problem, when players put item in the trade GUI, then change the money amount, the items that were in the trade GUI disappear

**Comment by catterz** [comment]
Is there a previous version that works with 1.13.2 that I can use in the meantime? This bug is preventing me going live with the plugin on my server otherwise and apart from that it's really great!

**Comment by CodingAir** [comment]
No, I don’t think so. I‘ll update this today.

**Comment by catterz** [comment]
Works great, thanks!
