### ISSUE TITLE
NBT tag support

### ISSUE THREAD

**Issue by jeannen** [CodingAir/TradeSystem#110]
Hey !
That would be cool to support NBT tags, like unbreakable, costom model data etc...

That way, we could create better GUIS ! :)

**Comment by CodingAir** [comment]
Thank you for your idea!

**Comment by jeannen** [comment]
Hey ! :)

Any update on that ? ^^

**Comment by CodingAir** [comment]
Working currently on my WarpSystem update, maybe I'll find some time for this on this weekend.
Sorry for this delay!

**Comment by jeannen** [comment]
Okay ! :)

Also, not related to this suggestion, but a in-range radius would be cool (so players need to be like 5 blocs from each other to be able to /trade)

**Comment by CodingAir** [comment]
Just take a look into the config.yml ;)

**Comment by jeannen** [comment]
Oh, my bad then :P

**Comment by CodingAir** [comment]
Unbreakable tag and custom model data implemented

**Comment by jeannen** [comment]
Thanks ! :D
