### ISSUE TITLE
Cant edit config files

### ISSUE THREAD

**Issue by blackshot** [CodingAir/TradeSystem#131]
i dont know why when i edit the Config.yml it restores the default config. also i suggest add a /trade reload or something like. 

Using 1.1.4 downloaded from spigot today

**Comment by CodingAir** [comment]
I’ll check this.

**Comment by Sandman224** [comment]
I have same exact issue. It is weird because the config worked just fine until I did some server maintenance and the plugin reset its config file. I would love a fix!

**Comment by CodingAir** [comment]
I'll update my WarpSystem first.

Maybe a week.

**Comment by CodingAir** [comment]
You can already reload my plugin with "/tradesystem reload" or "/ts reload".

Tested it and maybe I did some changes with my api or it already works...
