### ISSUE TITLE
QuitEvent Error triggering

### ISSUE THREAD

**Issue by blackshot** [CodingAir/TradeSystem#136]
10.02 02:00:35 [Server] ERROR Could not pass event PlayerQuitEvent to TradeSystem vB1
10.02 02:00:35 [Server] INFO java.lang.NullPointerException: null
10.02 02:00:35 [Server] INFO at me.soul.tradesystem.listeners.LeftListener.onLeft(LeftListener.java:18) ~[?:?]
10.02 02:00:35 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1019.execute(Unknown Source) ~[?:?]
10.02 02:00:35 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerList.disconnect(PlayerList.java:410) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1501) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.disconnect(PlayerConnection.java:282) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.disconnect(PlayerConnection.java:253) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:197) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1269) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-93]
10.02 02:00:35 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by CodingAir** [comment]
"me.soul.tradesystem.listeners.LeftListener.onLeft(LeftListener.java:18)" It's not my tradesystem.
