### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by boyanigl** [CodingAir/TradeSystem#157]
It is happening on random interval it can happen on the 2nd minute from the starting on the server and for now the best is on 8th hours.
Crash : https://pastebin.com/U1GKc0Ua

**Comment by CodingAir** [comment]
Hey, would be awesome if you could try a hotfix (Discord: CodingAir#0281).

**Comment by franxyk** [comment]
I have the same problem the server crashes randomly.
Crash to server:
https://pastebin.com/LYCjmbcR

**Comment by CodingAir** [comment]
Please head into my [discord server](https://discord.gg/aHpVRC2) to tradesystem > dev-builds and try my hotfix.

**Comment by franxyk** [comment]
I don't know how to replicate the error, therefore I don't know how to test it.

**Comment by CodingAir** [comment]
> I don't know how to replicate the error, therefore I don't know how to test it.

Just use my hotfix. If you don’t get further crashes it should be fine.

**Comment by franxyk** [comment]
> 
> 
> > I don't know how to replicate the error, therefore I don't know how to test it.
> 
> Just use my hotfix. If you don’t get further crashes it should be fine.

Where can I get that version?

**Comment by CodingAir** [comment]
> Please head into my [discord server](https://discord.gg/aHpVRC2) to tradesystem > dev-builds and try my hotfix.

Here.
