### ISSUE TITLE
Error on load TradeSystem 1.1.13 (tacospigot 1.8.8)

### ISSUE THREAD

**Issue by J4im3x0** [CodingAir/TradeSystem#186]
I was using the 1.1.12 TradeSystem, so I decided to update, but sadly the newer version of the plugin does not get loaded in 1.8.8 tacospigot https://pastebin.com/j8caviC2
I tried removing old files, anyways the error persists.

**Comment by haeiven** [comment]
Your pastebin is not working for me, but i've the same problem: https://paste.soleria.eu/axakewivih.css

Best regards,

**Comment by J4im3x0** [comment]
My bad, the pastebin is not working, but anyways is the same error as me,

Thanks for your reply, I hope that the developer could see this issue.

**Comment by CodingAir** [comment]
Appears only on TacoSpigot

**Comment by CodingAir** [comment]
@haeiven @J4im3x0 Please check my latest hotfix from my discord (#dev-builds)

**Comment by haeiven** [comment]
Still not working for me: https://paste.soleria.eu/pufanehane.md

**Comment by CodingAir** [comment]
Please try another build from my discord server (if you use my WarpSystem you must update to a dev build too)
