### ISSUE TITLE
[Plugin-Breaking Issue] Native plugin placeholders do not work if PAPI is installed

### ISSUE THREAD

**Issue by Leomelonseeds** [CodingAir/TradeSystem#201]
Hello there,

Messages that include native plugin placeholders and that are run through the PAPI.convert method in PAPI.java will not have their placeholders processed if PlaceholderAPI is installed.

This is because when PAPI parses a message, it will convert all characters following a percent "%" character and before a space character into lowercase. For example, a message saying "%PLAYER% says hi" will be parsed into "%player% says hi".

Because all native plugin placeholders are uppercase, and the methods used to replace these placeholders are case-sensitive, this effectively means that none of the placeholders will work. It is also detrimental to the "/trade [player]" command, because in the TradeCMD class on line 349 you split the string on the expression "%ACCEPT%" which doesn't exist since it has been converted to "%accept%" by PAPI. As String.split() is case-sensitive, this means that the array a1 will be of size 1, and line 361 will throw an ArrayIndexOutOfBoundsException since you try to reference a1[1]. This error happens when anyone tries to use /trade [player].

The simplest and most effective workaround would probably be to change all your placeholders to lowercase in my opinion.

I spent a lot of time trying to figure this problem out, and I would appreciate if you pushed a fix soon. Thanks for your time.

**Comment by CodingAir** [comment]
Fixed and uploaded.
