### ISSUE TITLE
Missing "User wants to trade" message

### ISSUE THREAD

**Issue by OoLunar** [CodingAir/TradeSystem#219]
**Describe the bug**
The recipient of the trade request is never told that the issuer wishes to trade. There is no "User wants to trade." only "Trade request expired"

**To Reproduce**
1. Startup a Paper 1.16.3 server
2. Do /trade OoLunar
3. Stop and wait for "Request expired"
4. OoLunar will report that they never got a trade request, only "trade expired."

**Expected behavior**
/trade OoLunar
"OoLunar wants to trade"

**Screenshots**
N/A

**Additional context**
N/A

**Comment by CodingAir** [comment]
Hi, I can't get this reproduced. Please add me on Discord (CodingAir#0281).

**Comment by OoLunar** [comment]
Friend request sent!

**Comment by CodingAir** [comment]
Works fine.
