### ISSUE TITLE
Fancy countdown doesn't work

### ISSUE THREAD

**Issue by JasonHorkles** [CodingAir/TradeSystem#232]
**Describe the bug**
The fancy countdown placeholder that's in the default English file doesn't work

**To Reproduce**
1. Start a trade
2. See that the default placeholder isn't parsed

**Expected behavior**
It should be parsed to show the seconds

**Screenshots**
![image](https://user-images.githubusercontent.com/51760372/100957005-f7cd3a80-34d6-11eb-838e-0b64af15904d.png)

**Additional context**
N/A

**Comment by CodingAir** [comment]
Please join my Discord server and use my lateste dev build. Thank you!
