### ISSUE TITLE
Add ElementalGems and TokenManager to tradesystem

### ISSUE THREAD

**Issue by TenReeez** [CodingAir/TradeSystem#235]
Gday.

Could you please add the ability for players to trade ElementalGems as well as Tokenmanager to your tradesystem plugin.

Thankyou.

ElementalGems: https://www.spigotmc.org/resources/%E2%9C%85-50-off-sale-extended-%E2%9C%85-%E3%80%8Belementalgems-1-8-1-16-gem-shops-upgrades-api-rewards-more-%E3%80%8A.80556/

TokenManager: https://www.spigotmc.org/resources/tokenmanager.8610/

**Comment by CodingAir** [comment]
Bumped

**Comment by CodingAir** [comment]
ElementalGems has no public API. I've contacted the author but I'll close this issue for now and reopen it when I got an answer.
TokenManager will still be implemented.
