### ISSUE TITLE
Every item with custom name in GUI starts with the Â character

### ISSUE THREAD

**Issue by LeonardoPantani** [CodingAir/TradeSystem#239]
**Describe the bug**
Every item with a name in the trade GUI starts with a "Â" character.

**To Reproduce**
Send a trade to someone, let the other person accept it and hover each item with a name inside the layout.

**Expected behavior**
Items should have their names as written in the lang file.

**Screenshots**
![image](https://user-images.githubusercontent.com/35602340/103216277-f6483400-4915-11eb-9ec2-748741c2de28.png)

**Additional context**
I'm using the latest hotfix (december 27th) with default ENG language.

**Comment by galexrt** [comment]
Seems that this issue is independent of the language file. We are having the same issue with the German `GER` language file. Also on the latest v1.2.1 Hotfix-2 version.

**Comment by galexrt** [comment]
@CodingAir Yep, the default GER file.
