### ISSUE TITLE
Problem with items in GUI while trade

### ISSUE THREAD

**Issue by MastereQ1337** [CodingAir/TradeSystem#241]
When he puts in, for example, 1 diamond, and then adds 5 diamonds, it still shows that I have 1 diamond. For it to show 6 diamonds, I have to move the stack to e.g. another place. Just like I add 32 diamonds to exchange, I will take se 16 and it shows 32 instead of 16. I think it's understandable.

![syf2](https://user-images.githubusercontent.com/41511267/104517705-d2b00980-55f6-11eb-9821-09d63a652efe.png)

**Comment by CodingAir** [comment]
Please try my latest hotfix from my Discord.
