### ISSUE TITLE
<Title>Trade Won't get complete 

### ISSUE THREAD

**Issue by Tuurkevg** [CodingAir/TradeSystem#244]
when you both press on accept trade there happens nothing, and i do 
not see a countdown this is the error how can i fix this?
![Schermafbeelding 2021-01-25 om 16 23 48 2](https://user-images.githubusercontent.com/77327545/105726172-11fd2500-5f2a-11eb-88ee-2f6d5b561791.png)

**Comment by CodingAir** [comment]
Issue is fixed with my latest hotfix on my Discord.
