### ISSUE TITLE
Placeholders broken on 1.2.2 / 1.16.5

### ISSUE THREAD

**Issue by s1h4d0w** [CodingAir/TradeSystem#249]
**Describe the bug**
Placeholders seem to be broken, messages will show %PLAYER% and %ACCEPT% instead of the correct values. Running latest Paper 1.16.5

**To Reproduce**
1. Invite a player to trade
2. See the broken placeholder

**Expected behavior**
Placeholders working

**Screenshots**
![2021-02-25 21_08_49-Minecraft_ 1 16 5 - Multiplayer (3rd-party Server)](https://user-images.githubusercontent.com/5654654/109211023-f184ec80-77ad-11eb-971b-0cf1e634cd61.png)

**Discord contact**: lepel#5455

**Comment by CodingAir** [comment]
All placeholders must be lower case. You can either delete the language file and the plugin creates a new one or you replace all upper case variables into lower case.
