### ISSUE TITLE
Anvil GUI placeholder ignoring

### ISSUE THREAD

**Issue by ChefMC** [CodingAir/TradeSystem#250]
Hello, would be nice if you add feature for start trading by right-clicking player. When you right-click player, you will see message in chat with approving of sending request to player for trade:

Do you want to trade with %player%? [Yes] [No]

If you press "Yes", request will be sent. That idea is needed because players too lazy to search and learning for all commands and keep in mind them. Most of them just will don't know about trade feature, but will can see about it when they right-click anybody.

And also my idea compatible with other plugins that use right-clicking players for it's own purposes (because of that idea will don't open dialog directly, it will ask you before - do you really want to trade).

And while trade is not successed/cancelled, players can directly right-click each other to instantly resume trading dialog (with event cancelling, because other plugins will can open their dialogs too).

-----------------------------------------------------

`And while trade is not successed/cancelled, players can directly right-click each other to instantly resume trading dialog (with event cancelling, because other plugins will can open their dialogs too).`

Will be nice if trade cancelling button will be shown in chat too. Because while trade is not successed/cancelled, right-clicking player (which you are trading with) will be blocked for other plugins. So player will always see where he can cancel trade request after he accepted it.

Also will be nice to add trading timeout (if trade dialog not opened for 60 seconds - cancel trading with message "Trading with %player% was timed out. [Trade again]").

----------------------------------------------

And make also not required to erase "enter price" text in anvil GUI. Just add space in the end of text, so players will can to input price after that text and when they submitting entered cost, text just replacing and only number will stay. Because it too annoying to erase that text. Make it automatically and just parse number of cost from all string.

"Enter price here... " => "Enter price here... 50 ,35asd" => 50.35

String priceStr = anvilGUItext.replace(defaultText, ""/* important! because default text contains "..." */).replaceAll("[^0-9\.\,]+", "").replace(",", ".");

Then get price as number via
Double.parseDouble(priceStr) or Float.parseFloat(priseStr)

**Comment by Faun471** [comment]
> Hello, would be nice if you add feature for start trading by right-clicking player.

If you haven't yet, you can enable this in the config.
```yaml
  Action_To_Request:
    Shift_Rightclick: true 
```

**Comment by CodingAir** [comment]
Done with #276
