### ISSUE TITLE
Players are able to bypass required trade distance

### ISSUE THREAD

**Issue by farum12** [CodingAir/TradeSystem#251]
**Describe the bug**
Players are able to bypass required trade distance by sending /trade [playername] within allowed distance, then teleporting outside required distance. Second player is able to send /trade accept.

**Prerequisites:**
- Player plX
- Player plY
- distance_in_blocks set to 5

**To Reproduce**
1. Both players plX and plY are standing within radius of required distance.
2. Player plX issues command /trade plY.
3. Player plX goes outside the maximum radius (eg. distance between plX and plY is 20).
4. Player plY accepts trade by clicking "Accept" in message appearing in chat.
5. Players are able to trade their items.

**Expected behavior**
Player plY is not able to click "Accept" chat message, as the plX is now outside the required distance. 
Maximum distance is verified once again while plY is outside the radius.

**Screenshots**
None.

**Additional context**
On server I have PvP Arena, which gives players custom gear on start and takes it away on finish. If players reproduce the issue as described in steps - they are able to dupe items (send trade request, go to arena, gear up, accept request). 

**Discord contact**: Farum#5463

**Comment by CodingAir** [comment]
You can download a new build from by discord

**Comment by farum12** [comment]
Thanks!
