### ISSUE TITLE
Trading experience doesn't work in my server

### ISSUE THREAD

**Issue by OmarAlsh** [CodingAir/TradeSystem#254]
**Describe the bug**
When using Exp as the highest priority economy system, the trading layout shows the item that means that there is no active economy system.

**To Reproduce**
1. Create a layout with money trading.
2. Set Exp as the highest priority econ system
3. Attempt to trade experience points in game

**Expected behavior**
Should open a prompt to enter an amount of exp and let you trade it.

**Screenshots**
![image](https://user-images.githubusercontent.com/80933401/111721993-5c6a9600-8837-11eb-867c-86606fbed162.png)
![image](https://user-images.githubusercontent.com/80933401/111722113-92a81580-8837-11eb-9f1e-510bc31f6e82.png)
![image](https://user-images.githubusercontent.com/80933401/111722211-c420e100-8837-11eb-8e02-e1dcdf10eb3c.png)

**Discord contact**: alshehabibi#4444

**Comment by CodingAir** [comment]
Yeah, check your last image of your config :D
![image](https://user-images.githubusercontent.com/23747243/116818306-0ba2c880-ab6b-11eb-8f80-a7512e74282e.png)
