### ISSUE TITLE
Players can't use /trade or accept and decline trades.

### ISSUE THREAD

**Issue by Kriptiq** [CodingAir/TradeSystem#255]
**Describe the bug**
Players on the server can not use /trade or click "accept" and "deny" trades. When a player tries to use /trade receives error "This command only accessible in survival mode!" They are all in survival mode when trying to use. From testing only works in OP. When trying to trade a player as OP, player then receives the same error for trying to click "accept" or "deny".

**To Reproduce**
Unsure.

**Expected behavior**
Player should be able to use /trade and  get message other player was invited. The other player should be able to click "accept" and then get a trade window or "deny" cancelling the trade.

**Screenshots**
Errors:
![error](https://user-images.githubusercontent.com/81416196/112620484-9539da80-8df6-11eb-8c95-ac3644eb6b65.png)
![error2](https://user-images.githubusercontent.com/81416196/112621059-4e98b000-8df7-11eb-8cb2-09e706fae5bd.png)
From Server.Properties:
![server](https://user-images.githubusercontent.com/81416196/112623044-daabd700-8df9-11eb-8e70-1ffc894b9a67.png)

Current config [https://pastebin.com/f1QFqwYJ](url)

**Additional context**
I've so far tried adding all gamemodes to the config for allowed gamemodes. I've tried turning off requiring permissions. I've tried deleting all the config files and respawning. Did not resolve issue.

**Discord contact**: <name>Kriptiq#<id>0438

**Comment by CodingAir** [comment]
The message "This command only ..." does not belong to my plugin. You'll need to check your other plugin.
