### ISSUE TITLE
Sign GUI Implementation

### ISSUE THREAD

**Issue by BySebt** [CodingAir/TradeSystem#260]
**Is your feature request related to a problem? Please describe.**
The usage of the anvil GUI requires an extra click to focus on the text, making it hard to navigate

**Describe the solution you'd like**
Use a sign gui https://www.spigotmc.org/resources/signgui.17781/
Video Demonstration https://youtu.be/V34kdcTN6jk

**Discord contact**: SeaLegend#3096

**Comment by dorsax** [comment]
I see this question popping up more frequently in many plugin support channels, and all referenced code is the outdated and not maintained 1.8 plugin on SpigotMC. No maintainer agreed thus far. Is there any Ressource you can provide to make life easier for us guys trying to implement that request?

**Comment by BySebt** [comment]
https://www.spigotmc.org/resources/%E2%9A%A1-auctionmaster-2-%E2%9A%A1-1-8-1-16-auctions-categories-bin-admin-view-fully-configurable.84784/

This plugin uses signs as input/

Source: 
[AuctionMaster (2).zip](https://github.com/CodingAir/TradeSystem/files/6408804/AuctionMaster.2.zip)

**Comment by CodingAir** [comment]
Gonna give it a try!

**Comment by CodingAir** [comment]
Oops
