### ISSUE TITLE
Title of Trading Inventory has a bugged placeholder.

### ISSUE THREAD

**Issue by Tirco** [CodingAir/TradeSystem#270]
**Describe the bug**
![image](https://user-images.githubusercontent.com/8375039/117533823-1fc54a80-afef-11eb-8c25-f6e914828055.png)

The buttons are from an inventory sorting mod, issue happens without the mod as well.

**Comment by Pudiaz** [comment]
Same thing is happening to me

**Comment by CodingAir** [comment]
Fixed with #267
