### ISSUE TITLE
Thread Netty Epoll Server IO #2 failed thread check for reason: Asynchronous set type call

### ISSUE THREAD

**Issue by iGabyTM** [CodingAir/TradeSystem#277]
Error: https://paste.helpch.at/usahipipex.hs
Server version: `git-Tuinity-"1382473" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
Plugin version: `1.3.2`

I would give more details about how this happens or how to reproduce it but I just saw it in console a few times after updating to 1.3.2

**Comment by XC012** [comment]
same error but name is "Thread Netty Epoll Server IO #0 failed thread check for reason: Asynchronous set type call" 
- tuinity 1.16.5

**Comment by amarcais53** [comment]
when this error come we can dupe signs where we write money
