### ISSUE TITLE
BUG inventory

### ISSUE THREAD

**Issue by kedavlar** [CodingAir/TradeSystem#294]
VERSION: 2.0.1

BUG: Sometimes when someone makes a trade, after making the trade the trade can no longer transfer items to the chests. I dont know how it happend, its random from what i know

**Comment by CodingAir** [comment]
Sometimes, this will be blocked when the trade partner cannot take the items.

![image](https://user-images.githubusercontent.com/23747243/121235782-857a5000-c895-11eb-89b8-dbba2a11d856.png)
Please check this setting.

**Comment by kedavlar** [comment]
i already have this setting to true

**Comment by CodingAir** [comment]
Same as #299
