### ISSUE TITLE
[DUPE] Exp trade

### ISSUE THREAD

**Issue by BlackBaroness** [CodingAir/TradeSystem#306]
**Describe the bug**
The exchange of experience is wrong. When player A gives 10 levels to Player B (who already has 15 levels), he gets level 25. But this is wrong. Experience levels are not equal

**Comment by fra130701** [comment]
Already reported:
https://github.com/CodingAir/TradeSystem/issues/290

**Comment by CodingAir** [comment]
> Already reported:
> #290

Thanks
