### ISSUE TITLE
Paper found in the anvil menu is thrown to the ground

### ISSUE THREAD

**Issue by xPoyraz** [CodingAir/TradeSystem#308]
**Describe the bug**
The paper in the anvil menu can be thrown to the ground.

**Screenshots**
https://discord.com/channels/578230584871092235/585916390083526796/859033311183896586

**Discord contact**: Poyraz#3391

**Comment by CodingAir** [comment]
Still works fine for me. Do you have any other plugins that might interfere here?

**Comment by iVillager** [comment]
This happened to me with TradeProxy. You can the paper from the anvil gui, then you can put any other item, rename it and it gets duped. This can be reproduced by yourself, as it still works.
