### ISSUE TITLE
Add templates for the GUI

### ISSUE THREAD

**Issue by dorsax** [CodingAir/TradeSystem#309]
**Is your feature request related to a problem? Please describe.**
Lots of users need only Vault trading to be enabled and not both EXP and Vault and struggle to use the layout editor at all.

**Describe the solution you'd like**
Expand the command to create layouts like so:
`/tradesystem layout createfromtemplate <templatename> <name>`
Templatename can be like:
- minimal
- vault
- exp 
- EssentialsX

And the templates would contain the features they need. When issued, the command will open a layout prefilled with the needed icons and functions. You can start with a simple one. The could be located in the plugin folder /templates and they would be shareable by anyone.

**Describe alternatives you've considered**
Expanding the wiki is not very intuitive and a lot of users do never even ask. So the usage of the plugin may considerably drop by that approach.

**Comment by CodingAir** [comment]
What about adding a few layouts by default and making them configurable?

**Comment by dorsax** [comment]
That's even better. As I can see they are not stored atm? I guess you could store them as .yaml, too. 

Maybe at setup you have to select one actively so nobody will be in the state that nothing works?
For setups migrating from a version from before the editor or new setups a need to select, and for migrating setups from other versions a hint to the console or admins?

**Comment by CodingAir** [comment]
![image](https://user-images.githubusercontent.com/23747243/124192686-f512e200-dac5-11eb-8750-4fa7be78bfe4.png)
This message will be sent to players with the notify permission 5 seconds after joining the server if there was an empty layout file in the loading process.
