### ISSUE TITLE
[Issue] 1.17.1 Not working

### ISSUE THREAD

**Issue by Starkenz** [CodingAir/TradeSystem#313]
**Describe the bug**
1.17.1 not working on paper version.

**To Reproduce**
https://pastebin.com/mVyvFy4Q

**Additional context**
Hotfix 1   -   v2.0.2
Paper 1.17.1 #85

**Discord contact**: StarkeN#7173

**Comment by YajTPG** [comment]
I can confirm I get the same error on PaperMC 1.17.1
