### ISSUE TITLE
Sign GUI not opening

### ISSUE THREAD

**Issue by BySebt** [CodingAir/TradeSystem#319]
**Describe the bug**
Bug: SignGUI Not opening:

- Trade System 2.0.4
- No other plugin that uses a sign as input
- Latest version of Protocolib

It also seems to say "you have no exp" when someone has an empty balance on vault. (Essentials Economy)

**To Reproduce**
1. Delete the Config folder so a new one can generate
2. Change config to "SIGN"
3. /ts layout activate Standard-Vault
4. Make sure Vault and an economy plugin is installed
5. When clicked on gold, the sign won't open.

**Video**
https://i.imgur.com/b7qMH2k.mp4

**Discord contact**: SeaLegend#30966

**Comment by CodingAir** [comment]
Which MC version and server type (spigot, paper, ...) do you use?

**Comment by BySebt** [comment]
> Which MC version and server type (spigot, paper, ...) do you use?

PaperSpigot 1.8.8

**Comment by BySebt** [comment]
Its been like half a year, any updates?
