### ISSUE TITLE
Anvil GUI: paper can be grabbed

### ISSUE THREAD

**Issue by dorsax** [CodingAir/TradeSystem#323]
**Describe the bug**
The Anvil GUI does not prevent the user to grab the paper, thus rendering the GUI useless afterwards.

https://cdn.discordapp.com/attachments/585916415786221569/868835632871538688/TradeSystem.mp4

**Discord contact**: Jxstn#0701

Paper 1.16.5#783 
TradeSystem 2.0.4-Hotfix 2

**Comment by CodingAir** [comment]
Same as #308
