### ISSUE TITLE
Add API (for payment/currency providers)

### ISSUE THREAD

**Issue by BrainStone** [CodingAir/TradeSystem#324]
**Is your feature request related to a problem? Please describe.**  
I would like to add support for different kinds of currency. But as of right now this is only possible by modifying this plugin.

**Describe the solution you'd like**  
I would love to have an API to be able to add currencies to the system. Ideally there are two ways:
- Adding a currency in a way so that TradeSystem parses the user input as it would normally
- Adding a currency in a way so that the plugin adding the currency parses the user input.

My concrete use case for this would be a time based currency. So suffixes like k or G just don't make sense.  
Though I'm sure there are many more use cases.

**Describe alternatives you've considered**  
Adding the support in this plugin directly. But that shifts the maintenance burden on you, which is not ideal.

**Discord contact**: BrainStone#6759

**Comment by CodingAir** [comment]
I just created a new event to register entire TradeIcons: TradeIconInitializeEvent

All registered icons can be used in the layout editor later on.
