### ISSUE TITLE
%player% placeholder

### ISSUE THREAD

**Issue by Eliott79** [CodingAir/TradeSystem#329]
The %player% placeholder display the name of the sender not the name of the receiver.

**Comment by CodingAir** [comment]
This issue occurs only when PlaceholderAPI is installed.

**Comment by CodingAir** [comment]
Works fine for me...

**Comment by denisdnu** [comment]
I have the same issue in the latest build.
When I send a trade request, it says, that it's me who was invited

**Comment by CodingAir** [comment]
@denisdnu Do you use the default language file?

**Comment by denisdnu** [comment]
No, but I didn't modify placeholders and it worked the same wrong with a default config
