### ISSUE TITLE
MySQL AutoReconnect

### ISSUE THREAD

**Issue by Regerta** [CodingAir/TradeSystem#338]
**Is your feature request related to a problem? Please describe.**
If Trade System lost connection to MySQL, it didn't reconnect and show lots of WARN on the console whenever user start a trade.
Console Log: https://paste.md-5.net/iyahapaqij.sql

**Describe the solution you'd like**
Add an option to enable MySQL AutoReconnect function on Config.yml

**Comment by CodingAir** [comment]
Fixed. You can download a new version from my Discord server or from [here](https://github.com/CodingAir/TradeSystem/actions/runs/1262322345).
