### ISSUE TITLE
Unable to trade items with Unbreakable NBT Tag with TradeProxy

### ISSUE THREAD

**Issue by sxphirus** [CodingAir/TradeSystem#345]
**Describe the bug**
Items with the Unbreakable NBT Tag cannot be traded and throw error
https://mclo.gs/HWwXiQM

**To Reproduce**
1. minecraft:give @p netherite_shovel{Unbreakable:1b}
2. /trade with a user on another server
3. See error & GUI does not open for whoever has the unbreakable item in their inventory

**Expected behavior**
Trade GUI opens and allows trade

**Additional context**
Latest Hotfix 2 build (v2.0.6)
Purpur 1.17.1

**Discord contact**: `Saphirus#0001`

**Comment by CodingAir** [comment]
Fixed with #346
