### ISSUE TITLE
config.yml corrupted/not working at all

### ISSUE THREAD

**Issue by raffel080108** [CodingAir/TradeSystem#355]
**Describe the bug**
Opening config.yml will simply show Error while running this#saveToString(). I tried deleting it and reloading the plugin, same thing happened

**Expected behavior**
The config.yml should not return an error and therfor be uneditable

**Screenshots**
![image](https://user-images.githubusercontent.com/62069283/148267888-9b78afd0-8607-4974-8838-cd01bb1d75f9.png)

**Additional context**
The error isn't the only thing that shows but the rest are just comments, so it's still a useless and uneditable config

**Discord contact**: raffel080108#4231

**Comment by HermitTHC** [comment]
I was also having this issue yesterday, I think it affects all of TradeSystem's `.yaml` files.

**Comment by raffel080108** [comment]
The file extension is `.yml` and I cannot confirm this as my layouts.yml file does not do this. I didn't edit it tho since the issue had occured so I'm not sure if it's because of that

**Comment by HermitTHC** [comment]
Oh yeah, my bad, I meant `.yml` files

**Comment by raffel080108** [comment]
I know, just mentioned it

**Comment by HermitTHC** [comment]
I personally think I had it happening for all of my yml files, though I removed the plugin and its folder from my server so I can't check

**Comment by CodingAir** [comment]
I already posted information about this. Please follow my guidelines on my discord in #talk.
