### ISSUE TITLE
[Feature Request] Possibility to accept trades with Sneak+RClick

### ISSUE THREAD

**Issue by klaidosHka** [CodingAir/TradeSystem#357]
**Describe the solution you'd like**
Just a simple ability to accept trades while `Sneaking and Right Clicking` the person, who asked to trade. Not going to lie, I didn't use this plugin for **some time**, but as far as I remember, even if there is trade requesting with `Sneaking and Right Clicking`, I don't think that the accepting of such way appeared yet anyways. And that is probably the only disadvantage versus other trading plugins that even are premium 🥺

**Describe alternatives you've considered**
I don't think there are any alternatives to this feature request, it is either that or... nothing? ...stay as it is 😩

**Additional context**
If such possibility appeared, there probably would be a need of toggleable option in the config and a way of editing messages when you get a trade from any person (which, probably, already exists).

**Discord contact**: `Klaidas.#9224`

**Comment by CodingAir** [comment]
You actually can accept trade requests using `Sneaking and Right Clicking`.

**Comment by CodingAir** [comment]
> If such possibility appeared, there probably would be a need of toggleable option in the config and a way of editing messages when you get a trade from any person (which, probably, already exists).
You can toggle this in your config too and the message of the trade request will be configured in your language file :v:
