### ISSUE TITLE
ERROR Could not pass event PlayerJoinEvent to TradeSystem v2.0.10

### ISSUE THREAD

**Issue by Sleepyflea** [CodingAir/TradeSystem#367]
**Describe the bug**
Could not pass player join event.

**To Reproduce**
1. run a 1.18.2 server
2. install trade system
3. join the server or try to trade

**Expected behavior**
no error in console

**Screenshots**
If applicable, add screenshots to help explain your problem.06.03 14:24:28 [Server] ERROR Could not pass event PlayerJoinEvent to TradeSystem v2.0.10
06.03 14:24:28 [Server] INFO java.lang.ClassCastException: class net.minecraft.network.protocol.EnumProtocolDirection cannot be cast to class io.netty.channel.Channel (net.minecraft.network.protocol.EnumProtocolDirection and io.netty.channel.Channel are in unnamed module of loader java.net.URLClassLoader @49097b5d)
06.03 14:24:28 [Server] INFO at de.codingair.tradesystem.lib.codingapi.player.data.PacketReader.inject(PacketReader.java:71) ~[TradeSystem_v2.0.10.jar:?]
06.03 14:24:28 [Server] INFO at de.codingair.tradesystem.lib.codingapi.server.listeners.PickItemListener.onJoin(PickItemListener.java:83) ~[TradeSystem_v2.0.10.jar:?]
06.03 14:24:28 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor79.execute(Unknown Source) ~[?:?]
06.03 14:24:28 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
06.03 14:24:28 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-"0ee6dda"]
06.03 14:24:28 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
06.03 14:24:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
06.03 14:24:28 [Server] INFO at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363) ~[paper-1.18.2.jar:git-Paper-"0ee6dda"]
06.03 14:24:28 [Server] INFO at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[paper-1.18.2.jar:git-Paper-"0ee6dda"]
06.03 14:24:28 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:305) ~[?:?]
06.03 14:24:28 [Server] INFO at net.minecraft.network.Connection.tick(Connection.java:567) ~[?:?]
06.03 14:24:28 [Server] INFO at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
06.03 14:24:28 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1610) ~[paper-1.18.2.jar:git-Paper-"0ee6dda"]
06.03 14:24:28 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-"0ee6dda"]
06.03 14:24:28 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1444) ~[paper-1.18.2.jar:git-Paper-"0ee6dda"]
06.03 14:24:28 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[paper-1.18.2.jar:git-Paper-"0ee6dda"]
06.03 14:24:28 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-"0ee6dda"]
06.03 14:24:28 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Discord contact**: SpicyChicken#3080

**Comment by LuluxClient** [comment]
Getting the same issue with 1.18.2
