### ISSUE TITLE
TradeProxy server error when adding items to trade UI

### ISSUE THREAD

**Issue by Dakotaa** [CodingAir/TradeSystem#380]
**Describe the bug**
When using TradeProxy and trading with a player on another server, putting an item into the trade UI will cause [this error](https://pastebin.com/VqBnFaBX) to pop up on the server that the other player is on.

The item does not show in the trade UI for the other player, and neither player receives any items upon trade completion.

The money and ready UI elements still update correctly cross-server.

**To Reproduce**
1. Have TradeProxy running with TradeSystem running on Server A and Server B.
2. Have player on Server A send a trade request to player on Server B.
3. Once player on Server B accepts request, have player on Server A add item to trade window.
4. Player on Server B does not see item in trade window, and error is thrown on Server B.

**Additional context**
[The discord conversation about this, for more info.](https://discord.com/channels/578230584871092235/585916390083526796/966189101739020328)

**Discord contact**: Dakota#8551

**Comment by CodingAir** [comment]
Should also affect #377
