### ISSUE TITLE
Add simple hook API for extra items of other plugins

### ISSUE THREAD

**Issue by CodingAir** [CodingAir/TradeSystem#51]
i.e. GriefPrevention

https://www.spigotmc.org/threads/trade-system-custom-layouts.327308/page-2

GriefPrevention is, as the name suggests, an anti-grief plugin in which players can claim any available land as long as they have sufficient claim blocks. Claim blocks are "virtual", similar to money so it's not a physical item. My suggestion is to allow players to give other players their claim blocks in the same way they can give money.

Plugin Download: https://www.spigotmc.org/resources/griefprevention.1884/
Plugin Source Code: https://github.com/TechFortress/GriefPrevention/

**Comment by Nerd2201** [comment]
Ok, so you want to allow players trading blocks from grief prevention? or trading claims? @CodingAir

**Comment by hwalker928** [comment]
Did this ever happen?

**Comment by CodingAir** [comment]
No, never got the spirit to finish that.
Feel free to participate ^^

**Comment by CodingAir** [comment]
Done with #276
