### ISSUE TITLE
(feature request) Split locales into separate language files

### ISSUE THREAD

**Issue by arboriginal** [CodingAir/TradeSystem#70]
Hello,

Just discover your plugin, seems to work fine (I'll test deeper and report you problems if any) but I saw the localisation could be much better:

- Move the `Language` (and maybe `Prefix`... not sure if it has to be) parameter into Config.yml
- Split Language.yml into language_en.yml and language_de.yml (*), or make a lang/{langcode}.yml

This will help localise your plugin in other languages. It's IMHO cleaner than everything in a single file for admins when there are more than a few sentences. And users could share and contribute their independent languages files easier.

To illustrate what I mean, you can check how Citizens2 manage locales files for example:
https://github.com/CitizensDev/Citizens2/tree/master/main/src/main/resources

You can for example in your `reloadConfig()` read `getConfig().getString("Language")`, then load the appropriate file in a list, or something like that. I've already did this king of implementation, I could try to find where it is in my chaos of not finished codes if needed :-)

But this is a suggestion and not a priority ;) Thanks for sharing this plugin with the community!

(*) I think it's better to use [ISO code](https://fr.wikipedia.org/wiki/ISO_3166-2) for language filenames, but it's a detail.
**Edit:** (replaced "files" by "filenames" in this sentence to be more clear).

**Edit:** Here is an example of a [separate lang file for french language](https://gist.github.com/arboriginal/3306d643684a1c94c31c3c159a17f721).
(fell free to reuse it if you want, it is yours!)

**Comment by CodingAir** [comment]
Thanks I will use this next time ;)

Omg question: Why ISO and not UTF_8? I changed that UTF_8 to add  symbols

**Comment by arboriginal** [comment]
In fact, I talk about ISO 3166-2 (a norm / standard) not about the ISO-XXXXX related to encoding. :)

> The purpose of ISO 3166-2 is to establish an international standard of short and unique alphanumeric codes to represent the relevant administrative (...) of all countries (...).

And sorry, I've just realised I put the french link... here is the english one:
https://en.wikipedia.org/wiki/ISO_3166-2

Of the german one, because your are:
https://de.wikipedia.org/wiki/ISO_3166-2

**Comment by CodingAir** [comment]
Ok, thanks. I'll take a look into it later.
