### ISSUE TITLE
TradingSystem Spam, and 1 little error.

### ISSUE THREAD

**Issue by Ricozaur** [CodingAir/TradeSystem#8]
Hey there again.

Next to your warp system plugin i've also started using your trading system plugin.
It's really good but there is just 1 thing and it would be better then any other trading plugin i have ever seen.

It's that you can spam players with trades.
I don't really think this is a big problem since there are anti-spam plugins i guess.
But it would be awesome to be implemented into the plugin.

I have already made a request for the WarpSystem Combat fix
But i'm just letting you know that it can become even better ;)

Oh yeah 1 last thingy..
There is an error in the language {i haven't touched the file) i'll show you a screenshot.

[​IMG] 
https://gyazo.com/fd00d49548b5f75a7a112ac0e105ff3d

And here are the spam messages:

[​IMG] 
https://gyazo.com/30f886b0c32b5e7ce6db5616012fc70b

**Comment by CodingAir** [comment]
Thanks for your contribution ;)

**Comment by Ricozaur** [comment]
Always ;D
