### ISSUE TITLE
Translating

### ISSUE THREAD

**Issue by Clyred** [CodingAir/TradeSystem#90]
It's imposible to use unicode in language.yml with any kinds of encoding. Can you please add unicode support?

**Comment by CodingAir** [comment]
Why do you need unicode? Couldn‘t you just use the translated characters?

**Comment by ClyRed** [comment]
I was trying to translate it to russian but plugin doesn't accept it :D And just replaces my language file with new one

**Comment by CodingAir** [comment]
I'm going to check this. Thank you for your bug report!
