### ISSUE TITLE
Items dupe with trading

### ISSUE THREAD

**Issue by Clyred** [CodingAir/TradeSystem#91]
It’s simple, but balance breaking.
Let’s see... Player1 have 5 stacks of items and Player2 have only 2 empty slots in inventory. Player1 initiates trade and offers those 5 stacks for nothing from Player2. Trade goes successfully and Player2 gets those 5 stacks and 3 of them falls on the ground. After a while (1-5 minutes) Player1 gets a copy of those 5 stacks back. How? I dunno but it works exactly as i wrote

**Comment by Daxxas** [comment]
Any news on this ? I can't use a trade plugin if there is a dupe glitch in it :/

**Comment by CodingAir** [comment]
You can avoid this by disabling "Drop_Items" in the config.

I didn‘t found a solution for this yet.

**Comment by CodingAir** [comment]
Fixed
